# Set the base image to use
FROM gcc:latest
# Copy the C program into the container
COPY Lab_5_Problem2.c .
# Compile the C program
RUN gcc -o Lab_5_Problem2 Lab_5_Problem2.c
# Set the command to run when the container starts
CMD ["./Lab_5_Problem2"]